language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r Signo *
  - mkdir -p deploy
  - mv Signo.zip deploy/Signo.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: studentable-webservice-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: spike-team/Signo
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: studentable-webservice-deploy
    key: Signo.zip
    bundle_type: zip
    application: studentable-webservice
    deployment_group: studentable-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: spike-team/Signo
      branch: master

notifications:
  email:
    recipients:
      - by091154@gmail.com