spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    log-request-details: true
custom:
  firebase:
    server_key: ${FIREBASE_SERVER_KEY}
